# Generated by Django 2.0.8 on 2018-09-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('billed_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('opera_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('ia_status', models.CharField(choices=[('I', 'In Progress'), ('S', 'Submitted'), ('A', 'Approved')], max_length=20)),
                ('work_status', models.CharField(choices=[('R', 'Requested IA'), ('W', 'Awating Approval'), ('A', 'Approved')], max_length=20)),
                ('nwa_code', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('approved_amount', models.IntegerField(default=0)),
                ('invoiced_amount', models.IntegerField(default=0)),
                ('residual_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='monthlybilling',
            name='opera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowtracker.project'),
        ),
    ]
